permissions:
  contents: write
name: Build and Release LUDOVSeeder

on:
  pull_request:
    types:
      - closed   # se déclenche quand une PR est fermée
    branches:
      - main     # mais uniquement si la PR cible `main`

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests mysql-connector-python

      - name: Build executable
        run: |
          pyinstaller --onefile --name LUDOVSeeder main.py
        shell: powershell

      - name: Copy config.json
        run: |
          echo { \"DB_HOST\": \"localhost\", \"DB_PORT\": 3306, \"DB_USER\": \"root\", \"DB_PASSWORD\": \"\", \"DB_NAME\": \"ludov_dev\" } > dist/config.json
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LUDOVSeeder
          path: dist/*

  release:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: LUDOVSeeder
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.${{ github.run_number }}
          name: "LUDOVSeeder v1.${{ github.run_number }}"
          body: "Version générée automatiquement après merge de PR."
          draft: false
          prerelease: false
          files: |
            dist/LUDOVSeeder.exe
            dist/config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest.json
        run: |
          echo "{\"version\": \"v1.${{ github.run_number }}\", \"url\": \"https://github.com/${{ github.repository }}/releases/download/v1.${{ github.run_number }}/LUDOVSeeder.exe\"}" > latest.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add latest.json
          git commit -m "Update latest.json to v1.${{ github.run_number }}"
          git push
